### PR TITLE
Phase 2

### PR DESCRIPTION
**Pull request by ehats**
Phase 2 of the challenge done.

This PR has the commits squashed, as opposed to
https://github.com/callebjorkell/codechallenge-riddler/pull/4

### CODE REVIEW

**Comment by callebjorkell** [comment]
Please fix commit and PR messages. Also refer to any old PR if you open a new one with the same content. Another option here would have been to force push the changes into the branch you had before so that it would have shown up on the old PR.

**Comment by ehats** [comment]
@callebjorkell Added some PR description.

**Comment by callebjorkell** [comment]
Commit message should still be fixed.

**Comment by callebjorkell** [comment]
Also I found at least one comment from #4 that hasn't been addressed. Please push (force) the squashed commit to #4 and re-open that instead so that it is possible to see what changes have been made.

I'll close this now.

**Comment by callebjorkell** [comment]
also "phase 2 of the challenge done" isn't more descriptive than "phase 2" :wink: In the commit message please describe the actual changes. It is good to refer to specs, JIRA tickets or other requirements, but it is not enough. 

for example:
> Add database connection
>
> Database connection to a postgres database added to fulfil requirements of the
> second iteration of the code challenge.

That is a minimal commit message. You have to remember that anyone could cherry-pick your commit and all of a sudden the commits are without any context if they just say "Phase 2". Please review the article that I posted in #4 regarding the commit messages.

**Pull request closed without merging**
