### PR TITLE
Code challenge phase 2

### PR DESCRIPTION
**Pull request by ehats**
Description:
https://github.com/ehats/codechallenge-riddler/blob/f1f674dd22f202c004f5e408660b24973f3f902d/README.md

Previous PRs: #5  and #4 
Changes in this PR:
- Commit messages updated
- Commits squashed by force pushing
- PR description updated

### CODE REVIEW

**Comment by ehats** [comment]
@callebjorkell Better?

**Comment by callebjorkell** [comment]
Yes, but a link really isn't a "stand alone description". That link might change any time. When this repo would move away from github, that commit says nothing anymore.

Also I asked you to re-open and push to #4, not create a new PR.

**Comment by ehats** [comment]
I'm reopening this one then

@callebjorkell

**Comment by ehats** [comment]
@callebjorkell @rasmusbergpalm
Phase 3 of the code challenge

AngularJS frontend for the project
Demo video for the website

**Comment by rasmusbergpalm** [comment]
To my untrained frontend eye this looks right.
:+1:

**Comment by callebjorkell** [comment]
In the future, please don't add new features to an already open PR. It makes reviews harder.

**Comment by callebjorkell** [comment]
I will trust @rasmusbergpalm though and declare this done.

:+1:

**Pull request merged**
